env-id: env-0
node-name: null
local-ip: null
netplan-config-file-path: /etc/netplan/00-installer-config.yaml
network-interface-card: null
wifi:
  name: null
  pwd: null
is-first-node: false
vip: 192.168.1.200
local-ip-gateway: 192.168.1.1
apiserver-advertise-address: 0.0.0.0
pod-network-cidr: 10.244.0.0/16
control-plane-endpoint: 192.168.1.200:8443
alived-master-node-ip: 192.168.1.101
master-high-availability:
  enable: false
  keepalived:
    priority: 100
    virtual-ipaddress: 192.168.1.200
    check-apiserver:
      apiserver-vip: 192.168.1.200
      apiserver-dest-port: 8443
  haproxy:
    nodes:
    - name: node-1
      ip: 192.168.1.101
      port: 6443
    - name: node-2
      ip: 192.168.1.102
      port: 6443
ingress-provider:
  enable: false
  keepalived:
    priority: 100
    virtual-ipaddress: 192.168.1.300
    check-ingress-provider:
      apiserver-vip: 192.168.1.300
      apiserver-dest-port: 80