
node-name: 
local-ip: 
netplan-config-file-path: /etc/netplan/00-installer-config.yaml #00-installer-config-wifi.yaml 
network-interface-card: 
wifi:
  name: 
  pwd:
local-ip-gateway: 192.168.1.1
is-first-node: false
apiserver-advertise-address: 0.0.0.0
pod-network-cidr: 10.244.0.0/16
control-plane-endpoint: 192.168.1.200:8443
master-high-availability:
  enable: false
  keepalived:
    priority: 101
    virtual-ipaddress: 192.168.1.200
    check-apiserver:
      apiserver-vip: 192.168.1.200
      apiserver-dest-port: 8443
  haproxy:
    nodes: 
      - node0 192.168.1.100:6443
      # - node1 192.168.1.101:6443