
node-name: 
local-ip: 
master-high-availability:
  enable: true
  keepalived:
    priority: 101
    virtual-ipaddress: 192.168.1.200
    check-apiserver:
      apiserver-vip: 192.168.1.200
      apiserver-dest-port: 8443
  haproxy:
    nodes: 
      - node0 192.168.1.100:6443
      # - node1 192.168.1.101:6443