
node-name: 
local-ip: 
local-ip-gateway: 192.168.1.1
network-interface-card: eth0
is-first-node: false
apiserver-advertise-address: 0.0.0.0
pod-network-cidr: 
control-plane-endpoint:
master-high-availability:
  enable: false
  keepalived:
    priority: 101
    virtual-ipaddress: 192.168.1.200
    check-apiserver:
      apiserver-vip: 192.168.1.200
      apiserver-dest-port: 8443
  haproxy:
    nodes: 
      - node0 192.168.1.100:6443
      # - node1 192.168.1.101:6443