apiVersion: v1
kind: PersistentVolume
metadata:
  name: cert-volume
  namespace: traefik
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 128Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cert-claim
  namespace: traefik
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi