
node-name: 
local-ip: 
master-high-availability:
  enable: true
  keepalived:
    priority: 100
    virtual-ipaddress: 192.168.1.200
    check-apiserver:
      apiserver-vip: 192.168.1.200
      apiserver-dest-port: 8443
  haproxy:
    nodes: 
      - 192.168.1.100
      # - 192.168.1.101
      # - 192.168.1.102